
// AUTO-GENERATED FILE — DO NOT EDIT
import BARISAN_NASIONAL_OF_MALAYSIA_BN_png from "@/images/BARISAN_NASIONAL_OF_MALAYSIA_BN.png";
import BEBAS_ARNAB_png from "@/images/BEBAS_ARNAB.png";
import BEBAS_BAJU_png from "@/images/BEBAS_BAJU.png";
import BEBAS_BUKU_png from "@/images/BEBAS_BUKU.png";
import BEBAS_CEREK_png from "@/images/BEBAS_CEREK.png";
import BEBAS_CINCIN_png from "@/images/BEBAS_CINCIN.png";
import BEBAS_GAJAH_png from "@/images/BEBAS_GAJAH.png";
import BEBAS_JAM_png from "@/images/BEBAS_JAM.png";
import BEBAS_KUDA_png from "@/images/BEBAS_KUDA.png";
import BEBAS_KUNCI_png from "@/images/BEBAS_KUNCI.png";
import BEBAS_MANGGIS_png from "@/images/BEBAS_MANGGIS.png";
import BEBAS_PEN_png from "@/images/BEBAS_PEN.png";
import BEBAS_POKOK_png from "@/images/BEBAS_POKOK.png";
import BEBAS_RUMAH_png from "@/images/BEBAS_RUMAH.png";
import BEBAS_TRAKTOR_png from "@/images/BEBAS_TRAKTOR.png";
import PAKATAN_HARAPAN_PH_png from "@/images/PAKATAN_HARAPAN_PH.png";
import PARTI_ASPIRASI_RAKYAT_SARAWAK_ASPIRASI_png from "@/images/PARTI_ASPIRASI_RAKYAT_SARAWAK_ASPIRASI.png";
import PARTI_BANGSA_MALAYSIA_PBM_png from "@/images/PARTI_BANGSA_MALAYSIA_PBM.png";
import PARTI_BERSATU_SASA_MALAYSIA_BERSAMA_png from "@/images/PARTI_BERSATU_SASA_MALAYSIA_BERSAMA.png";
import PARTI_BUMI_KENYALANG_PBK_png from "@/images/PARTI_BUMI_KENYALANG_PBK.png";
import PARTI_DAMAI_SABAH_SPP_png from "@/images/PARTI_DAMAI_SABAH_SPP.png";
import PARTI_GABUNGAN_RAKYAT_SABAH_GRS_png from "@/images/PARTI_GABUNGAN_RAKYAT_SABAH_GRS.png";
import PARTI_IMPIAN_SABAH_PIS_png from "@/images/PARTI_IMPIAN_SABAH_PIS.png";
import PARTI_KEBANGSAAN_SABAH_PKS_png from "@/images/PARTI_KEBANGSAAN_SABAH_PKS.png";
import PARTI_KERJASAMA_ANAK_NEGERI_ANAK_NEGERI_png from "@/images/PARTI_KERJASAMA_ANAK_NEGERI_ANAK_NEGERI.png";
import PARTI_KESEJAHTERAAN_DEMOKRATIK_MASYARAKAT_KDM_png from "@/images/PARTI_KESEJAHTERAAN_DEMOKRATIK_MASYARAKAT_KDM.png";
import PARTI_MAJU_SABAH_SAPP_png from "@/images/PARTI_MAJU_SABAH_SAPP.png";
import PARTI_PERPADUAN_RAKYAT_SABAH_PPRS_png from "@/images/PARTI_PERPADUAN_RAKYAT_SABAH_PPRS.png";
import PARTI_RUMPUN_SABAH_RUMPUN_png from "@/images/PARTI_RUMPUN_SABAH_RUMPUN.png";
import PARTI_SOLIDARITI_TANAH_AIRKU_STARSABAH_png from "@/images/PARTI_SOLIDARITI_TANAH_AIRKU_STARSABAH.png";
import PARTI_WARISAN_SABAH_WARISAN_png from "@/images/PARTI_WARISAN_SABAH_WARISAN.png";
import PERIKATAN_NASIONAL_PN_png from "@/images/PERIKATAN_NASIONAL_PN.png";
import PERJUANGAN_RAKYAT_PR_png from "@/images/PERJUANGAN_RAKYAT_PR.png";
import PERTUBUHAN_KINABALU_PROGRESIF_BERSATU_UPKO_png from "@/images/PERTUBUHAN_KINABALU_PROGRESIF_BERSATU_UPKO.png";
import PERTUBUHAN_PARTI_GEMILANG_ANAK_SABAH_GAS_png from "@/images/PERTUBUHAN_PARTI_GEMILANG_ANAK_SABAH_GAS.png";
import PERTUBUHAN_PERPADUAN_RAKYAT_KEBANGSAAN_SABAH_PERPADUAN_png from "@/images/PERTUBUHAN_PERPADUAN_RAKYAT_KEBANGSAAN_SABAH_PERPADUAN.png";

export const imageMap = {
  "BARISAN_NASIONAL_OF_MALAYSIA_BN.png": BARISAN_NASIONAL_OF_MALAYSIA_BN_png,
  "BEBAS_ARNAB.png": BEBAS_ARNAB_png,
  "BEBAS_BAJU.png": BEBAS_BAJU_png,
  "BEBAS_BUKU.png": BEBAS_BUKU_png,
  "BEBAS_CEREK.png": BEBAS_CEREK_png,
  "BEBAS_CINCIN.png": BEBAS_CINCIN_png,
  "BEBAS_GAJAH.png": BEBAS_GAJAH_png,
  "BEBAS_JAM.png": BEBAS_JAM_png,
  "BEBAS_KUDA.png": BEBAS_KUDA_png,
  "BEBAS_KUNCI.png": BEBAS_KUNCI_png,
  "BEBAS_MANGGIS.png": BEBAS_MANGGIS_png,
  "BEBAS_PEN.png": BEBAS_PEN_png,
  "BEBAS_POKOK.png": BEBAS_POKOK_png,
  "BEBAS_RUMAH.png": BEBAS_RUMAH_png,
  "BEBAS_TRAKTOR.png": BEBAS_TRAKTOR_png,
  "PAKATAN_HARAPAN_PH.png": PAKATAN_HARAPAN_PH_png,
  "PARTI_ASPIRASI_RAKYAT_SARAWAK_ASPIRASI.png": PARTI_ASPIRASI_RAKYAT_SARAWAK_ASPIRASI_png,
  "PARTI_BANGSA_MALAYSIA_PBM.png": PARTI_BANGSA_MALAYSIA_PBM_png,
  "PARTI_BERSATU_SASA_MALAYSIA_BERSAMA.png": PARTI_BERSATU_SASA_MALAYSIA_BERSAMA_png,
  "PARTI_BUMI_KENYALANG_PBK.png": PARTI_BUMI_KENYALANG_PBK_png,
  "PARTI_DAMAI_SABAH_SPP.png": PARTI_DAMAI_SABAH_SPP_png,
  "PARTI_GABUNGAN_RAKYAT_SABAH_GRS.png": PARTI_GABUNGAN_RAKYAT_SABAH_GRS_png,
  "PARTI_IMPIAN_SABAH_PIS.png": PARTI_IMPIAN_SABAH_PIS_png,
  "PARTI_KEBANGSAAN_SABAH_PKS.png": PARTI_KEBANGSAAN_SABAH_PKS_png,
  "PARTI_KERJASAMA_ANAK_NEGERI_ANAK_NEGERI.png": PARTI_KERJASAMA_ANAK_NEGERI_ANAK_NEGERI_png,
  "PARTI_KESEJAHTERAAN_DEMOKRATIK_MASYARAKAT_KDM.png": PARTI_KESEJAHTERAAN_DEMOKRATIK_MASYARAKAT_KDM_png,
  "PARTI_MAJU_SABAH_SAPP.png": PARTI_MAJU_SABAH_SAPP_png,
  "PARTI_PERPADUAN_RAKYAT_SABAH_PPRS.png": PARTI_PERPADUAN_RAKYAT_SABAH_PPRS_png,
  "PARTI_RUMPUN_SABAH_RUMPUN.png": PARTI_RUMPUN_SABAH_RUMPUN_png,
  "PARTI_SOLIDARITI_TANAH_AIRKU_STARSABAH.png": PARTI_SOLIDARITI_TANAH_AIRKU_STARSABAH_png,
  "PARTI_WARISAN_SABAH_WARISAN.png": PARTI_WARISAN_SABAH_WARISAN_png,
  "PERIKATAN_NASIONAL_PN.png": PERIKATAN_NASIONAL_PN_png,
  "PERJUANGAN_RAKYAT_PR.png": PERJUANGAN_RAKYAT_PR_png,
  "PERTUBUHAN_KINABALU_PROGRESIF_BERSATU_UPKO.png": PERTUBUHAN_KINABALU_PROGRESIF_BERSATU_UPKO_png,
  "PERTUBUHAN_PARTI_GEMILANG_ANAK_SABAH_GAS.png": PERTUBUHAN_PARTI_GEMILANG_ANAK_SABAH_GAS_png,
  "PERTUBUHAN_PERPADUAN_RAKYAT_KEBANGSAAN_SABAH_PERPADUAN.png": PERTUBUHAN_PERPADUAN_RAKYAT_KEBANGSAAN_SABAH_PERPADUAN_png,
} as const;

export type ImageFilename = keyof typeof imageMap;
